#!/bin/sh
# SPDX-License-Identifier: 0BSD
alias ls='ls --color=auto'
alias mkscript='"${SHRC}/mkscript"'
alias man='"${SHRC}/man"'
alias zigstd='"${SHRC}/zigstd"'
alias mcdata='"${SHRC}/mcdata"'

snbt () {
    "${SHRC}/snbt" --to "${@}"
}

nbt () {
    "${SHRC}/snbt" --from "${@}"
}

killfirefox () (
    kill -9 "$(ps --no-header -o pid -C firefox | head -n 1 | sed 's/^ \+//')"
    sleep 1
    kill -9 "$(ps --no-header -o pid -C firefox | head -n 1 | sed 's/^ \+//')"
)
