#!/bin/sh
# SPDX-License-Identifier: 0BSD
alias ls='ls --color=auto'
alias update-zig='"${SHRC}/update-zig"'
alias update-zls='"${SHRC}/update-zls"'
alias update-janet='"${SHRC}/update-janet"'

type julia >/dev/null && \
    alias julia='julia --history-file=no'

type ssh >/dev/null && [ "${TERM}" = 'alacritty' ] && \
    alias ssh='TERM=xterm-256color ssh'

type kak >/dev/null && {
    alias man='"${SHRC}/man"'
    alias zigstd='"${SHRC}/zigstd"'
    alias mkscript='"${SHRC}/mkscript"'
}

[ -e "${HOME}/.local/lib/minecraft-server" ] && {
    alias mcdata='"${SHRC}/mcdata"'
    alias snbt='"${SHRC}/snbt" --to'
    alias nbt='"${SHRC}/snbt" --from'
}

killfirefox () (
    kill -9 "$(ps --no-header -o pid -C firefox | head -n 1 | sed 's/^ \+//')"
    sleep 1
    kill -9 "$(ps --no-header -o pid -C firefox | head -n 1 | sed 's/^ \+//')"
)
