#!/bin/sh
# SPDX-License-Identifier: 0BSD
zls_dir="${HOME}/.local/store/zls"
printf 'Checking for ZLS install\n' >&2
if [ -e "${zls_dir}" ]; then
    # Pull updates to ZLS or its dependencies.
    printf 'Using ZLS install at %s\n' "${zls_dir}" >&2
    cd -- "${zls_dir}" || exit
    git pull --recurse-submodules >&2
else
    # Clone the repo so the script can be used on a fresh system.
    mkdir -p "$(basename -- "${zls_dir}")" || exit
    git clone --recurse-submodules 'https://github.com/zigtools/zls.git' "${zls_dir}" >&2 || exit
    cd -- "${zls_dir}" || exit
    git config pull.rebase false >&2
fi

# Always attempt to build, even if we didn't pull any updates. Zig caches builds,
# so if nothing else changed to force us to rebuild, this command is instant.
zig build -Drelease-safe -Ddata_version=master --prefix "${HOME}/.local"
