#!/bin/sh
# SPDX-License-Identifier: 0BSD
. "${SHRC}/util"
zls_dir="${HOME}/.local/store/zls"
try get_git_repo --update --submodules --display=ZLS zls 'https://github.com/zigtools/zls'
cd -- "${zls_dir}" && zig build -Drelease-safe -Ddata_version=master --prefix "${HOME}/.local"
