#!/bin/sh
# SPDX-License-Identifier: 0BSD
. "${SHRC}/util"
janet_dir="${HOME}/.local/store/janet"
try_set new_tag get_git_repo --update --new-tag --display=Janet janet 'https://github.com/janet-lang/janet'
[ -z "${new_tag}" -a -e "${janet_dir}/build/janet" ] || {
    export PREFIX="${HOME}/.local"
    try cd -- "${janet_dir}"
    silence make clean
    try make
    try make install

    sed -i '1c\
#!'"${HOME}/.local/bin/janet"'
    s/(and is-janet (dyn :auto-shebang))/is-janet/
    s/^\( *\)first-line \((if hardcode\)/\1(if-not (and auto-shebang (string\/has-prefix? "#!" first-line)) first-line)\n\1\2/
    ' "${HOME}/.local/bin/jpm"
}
