#!/bin/sh
# SPDX-License-Identifier: 0BSD

# Run `ln -f` if the destination is a symlink, or `ln -i` otherwise.
ln_Tfi () {
    mkdir -p "$(dirname -- "${1}")" || return
    if [ -L "${1}" ]; then
        ln -Tsrf -- "${2}" "${1}"
    else
        ln -Tsri -- "${2}" "${1}"
    fi
}
ln_fi () {
    ln_Tfi "${1}/$(basename -- "${2}")" "${2}"
}

cd "$(dirname -- "$(readlink -ne -- "${0}")")"

# Link files needed for correct system operation.
ln_Tfi "${HOME}/.profile" "$(pwd)/profile"
ln_Tfi "${HOME}/.zshenv" "$(pwd)/profile"
ln_Tfi "${HOME}/.zshrc" "$(pwd)/zshrc"
ln_Tfi "${HOME}/.gitconfig" "$(pwd)/gitconfig"
ln_Tfi "${HOME}/.gitignore" "$(pwd)/gitignore"
ln_fi "${HOME}/.local/share" "$(pwd)/shrc"

# Link personal scripts to make available in PATH.
for file in "$(pwd)/scripts/"*; do
    [ ! -e "${file}" ] && continue
    ln_fi "${HOME}/.local/bin" "${file}"
done

# Link personal Kakoune colorschemes.
for file in "$(pwd)/config/kak/colors/"*; do
    [ ! -e "${file}" ] && continue
    ln_fi "${HOME}/.config/kak/colors" "${file}"
done

# Link kakrc and its sub-files.
ln_fi "${HOME}/.config/kak" "$(pwd)/config/kak/kakrc"
ln_fi "${HOME}/.config/kak" "$(pwd)/config/kak/rc"

# Link license and gitignore templates.
ln_fi "${HOME}/templates" "$(pwd)/templates/gitignore"
ln_fi "${HOME}/templates" "$(pwd)/templates/licenses"
ln_fi "${HOME}/templates" "$(pwd)/templates/license-headers"
