#!/bin/sh
# SPDX-License-Identifier: 0BSD
. "./profile"

[ -e "${HOME}/.local/bin/zig" ] \
 || "${SHRC}/update-zig"

[ -e "${HOME}/.local/bin/janet" ] \
 || "${SHRC}/update-janet"

[ ! -e "${HOME}/.local/lib/janet/spork" ] \
 && [ -e "${HOME}/.local/bin/jpm" ] \
 && jpm install spork
